CREATE TABLE "AGENTS" ("ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY, "NAME" VARCHAR(255), "FULLNAME" VARCHAR(255), "SECRETNAME" VARCHAR(255), "EQUIPMENT" VARCHAR(255));

CREATE TABLE "CONTRACTS" ("ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY, "STARTDATE" VARCHAR(255), "ENDDATE" VARCHAR(255), "AGENT" BIGINT, "MISSION" BIGINT);

CREATE TABLE "MISSIONS" ("ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY, "TARGET" VARCHAR(255), "NECESSARYEQUIPMENT" VARCHAR(255), "DEADLINE" VARCHAR(255));